language: node_js
node_js:
- '0.10'
deploy:
  provider: npm
  email: bvdrucker@gmail.com
  api_key:
    secure: CZJWHAoLb7HBw/myKCvg7tUuW/B6skfEX30KAJnVAeGtP7YdW4s8sEwYUqR1Rz7HKJQz1r2yB/8xoBOeAAARZ4eUYRTYJ8LHOf15voajk/v+31OsUDxs80zpUzPxWHoSECgXdqxZ/yIwoTW3Hq8ou8u4d8g4BdqbvSsf6r0Mpew=
  on:
    tags: true
    repo: bendrucker/convex-firebase
    all_branches: true
after_success:
- npm install -g codeclimate-test-reporter
- codeclimate < ./coverage/lcov.info
env:
  global:
    secure: BtwYpSRoOKyG+s3rYeRKhnLyVswnoNjW/6KjbQ+d1Qnq7NM+eILcUn0g8LqoAlPKAFxViZ82+1Cl3VEk1LK+VhFT9vB2wUGkCGs+JM4nbnh42iiJC39j4r8KH4D17c8wwfU4qUY+yIpNIf3O5rZKxG74SnNqoFIs4Crnhx+qtGU=
